# Generated by Django 6.0.4 on 2026-04-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(max_length=150)),
                ('documentoIdentidad', models.CharField(max_length=50)),
                ('correoElectronico', models.EmailField(max_length=254)),
                ('fechaAsistencia', models.DateField()),
                ('horaIngreso', models.TimeField()),
                ('horaSalida', models.TimeField()),
                ('presente', models.BooleanField(default=False)),
                ('observaciones', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
