# Generated by Django 6.0.4 on 2026-04-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSolicitante', models.CharField(max_length=150)),
                ('documentoIdentidad', models.CharField(max_length=50)),
                ('correoElectronico', models.EmailField(max_length=254)),
                ('telefonoContacto', models.IntegerField()),
                ('asusto', models.CharField(max_length=100)),
                ('descripcionDetallada', models.CharField(max_length=200)),
                ('fechaSolicitud', models.DateTimeField()),
                ('archivoAdjunto', models.FileField(blank=True, null=True, upload_to='archivos/')),
            ],
        ),
    ]
